# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
     - checkout
     - setup_remote_docker
     - run: |
         TAG=0.1.$CIRCLE_BUILD_NUM
         docker build -t yenigul/hacicenkins:$TAG .
         echo "$dockerpass" | docker login --username $dockeruser --password-stdin
         docker push yenigul/hacicenkins:$TAG

    

workflows:
  # Name the workflow "welcome"
  buildocker:
    # Run the welcome/run job in its own container
    jobs:
      - build