# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  validate_config:
    docker:
      - image: circleci/buildpack-deps:focal
    parameters:
      regions:
        type: string
        default: "us-east-2 us-west-2"
      envs:
        type: string
        default: "stage prod"
    steps:
      - checkout
      - run:
          name: validate config
          command: |
            #set -e
            #pwd
            #curl -L -o scripts/yq  https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 && chmod 755 scripts/yq
            #chmod 755 scripts/validate.sh 
            #bash -x ./scripts/validate.sh us-east-2 stage
            for region in << parameters.regions >>
            do 
              for envs in << parameters.envs >>
              do
                echo "region: $region - env $envs"
              done
            done
      
  build:
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
     - checkout
     - setup_remote_docker
     - run: |
         TAG=$CIRCLE_SHA1
         docker build -t yenigul/hacicenkins:$TAG .
         echo "$dockerpass" | docker login --username $dockeruser --password-stdin
         docker push yenigul/hacicenkins:$TAG

    

workflows:
  # Name the workflow "welcome"
  buildocker:
    # Run the welcome/run job in its own container
    jobs:
      - validate_config
      - build:
          requires:
          - validate_config
           
