# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  validate_config:
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
      - checkout
      - run:
          name: validate config
          command: |
            set -e
            bash --version
            chmod 755 validate.sh && ./validate.sh
      
  build:
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
     - checkout
     - setup_remote_docker
     - run: |
         TAG=$CIRCLE_SHA1
         docker build -t yenigul/hacicenkins:$TAG .
         echo "$dockerpass" | docker login --username $dockeruser --password-stdin
         docker push yenigul/hacicenkins:$TAG

    

workflows:
  # Name the workflow "welcome"
  buildocker:
    # Run the welcome/run job in its own container
    jobs:
      - validate_config
      - build:
          requires:
          - validate_config
           